import { addIcons, OhVueIcon } from 'oh-vue-icons'
import {
  BiSunFill,
  BiMoonFill,
  BiChevronDown,
  BiSearch,
  BiStars,
  BiInfoCircle,
  BiMortarboard,
  BiCheck2Circle,
  BiInbox,
  BiListCheck,
  BiGem,
  BiPlusCircle,
  BiChatDots,
  BiEnvelope,
  BiChatText,
  BiJournalBookmarkFill,
  BiHouseDoor,
  BiJournalText,
  BiJournalBookmark,
  BiArrowRight,
  BiPencil,
  BiGear,
  BiBoxArrowRight,
  BiPersonCircle,
  BiPersonPlus,
  BiList,
  BiX,
  BiCart,
  BiPeople,
  BiDownload,
  BiCurrencyEuro,
} from 'oh-vue-icons/icons/bi'

addIcons(
  BiSunFill,
  BiMoonFill,
  BiChevronDown,
  BiSearch,
  BiStars,
  BiInfoCircle,
  BiMortarboard,
  BiCheck2Circle,
  BiInbox,
  BiListCheck,
  BiGem,
  BiPlusCircle,
  BiChatDots,
  BiEnvelope,
  BiChatText,
  BiJournalBookmarkFill,
  BiHouseDoor,
  BiJournalText,
  BiJournalBookmark,
  BiArrowRight,
  BiPencil,
  BiGear,
  BiBoxArrowRight,
  BiPersonCircle,
  BiPersonPlus,
  BiList,
  BiX,
  BiCart,
  BiPeople,
  BiDownload,
  BiCurrencyEuro,
)

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('VIcon', OhVueIcon)
})
